app/urls.py
from django.contrib import admin
from django.urls import path, include

from tasks.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("radios/", include("radio.urls")),
    path("twitch/", include("twitch.urls"))
]

radio/urls.py
from django.urls import path
from . import views as v

app_name = "radio"

urlpatterns = [
    path("", v.list_radios, name="list-radios"),
    path("", v.order_radios_by_dial, name="order-radios-by-dial"),
    path("", v.order_radios_by_name, name="order-radios-by-name"),
    path("", v.order_radios_by_id, name="order-radios-by-id"),
    path("add/", v.add_radios, name="add-radios"),
]

radio/models.py
from django.db import models



class City(models.Model):
    locality = models.CharField(
        "Localidade",
        max_length=30
    )

    def __str__(self):
        return self.locality

    class Meta:
        verbose_name = "Cidade"
        verbose_name_plural = "Cidades"


class Radio(models.Model):
    name = models.CharField(
        "Nome",
        max_length=20
    )
    dial = models.CharField(
        "Canal",
        max_length=5
    )
    cities = models.ForeignKey(
        City,
        on_delete=models.PROTECT,
        null=True, blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Rádio"
        verbose_name_plural = "Rádios"

radio/views.py
from django.shortcuts import render

from .models import Radio, City


def list_radios(request):
    template_name = 'radio/list_radios.html'
    # template_name = 'radio/hx/radio_result_hx.html'
    radios = Radio.objects.all()
    cities = City.objects.all()
    id_city = 0
    if request.GET.get('id_city'):
        # radios = Radio.objects.filter(cities=request.GET.get('id_city'))
        order_city = City.objects.filter(id=request.GET.get('id_city'))
        radios = Radio.objects.filter(cities=request.GET.get('id_city'))
        id_city = int(request.GET.get('id_city'))
    context = {
        'radios': radios,
        'cities': cities,
        'id_city': id_city
    }
    return render(request, template_name, context)


def add_radios(request):
    template_name = 'radio/list_radios.html'
    name = request.POST['name']
    dial = request.POST['dial']
    Radio.objects.create(
        name=name,
        dial=dial
    )
    radios = Radio.objects.all()
    context = {
        'radios': radios
    }
    return render(request, template_name, context)


def order_radios_by_id(request):
    template_name = 'radio/list_radios.html'
    radios = Radio.objects.all().order_by('id')
    context = {
        'radios': radios
    }
    return render(request, template_name, context)


def order_radios_by_dial(request):
    template_name = 'radio/hx/radio_result_hx.html'
    radios = Radio.objects.all().order_by('-dial')
    context = {
        'radios': radios
    }
    return render(request, template_name, context)

def order_radios_by_name(request):
    template_name = 'radio/list_radios.html'
    radios = Radio.objects.all().order_by('-name')
    context = {
        'radios': radios
    }
    return render(request, template_name, context)

templates/radio/list_radios.html
{% extends 'base.html' %}

{% block content %}
    <h3>Listas as rádios</h3>
    <table class="table">
        <thead>
            <tr>
                <th hx-get="{% url 'radio:order-radios-by-id' %}"
                    hx-target="#radioTbody"
                    hx-indicator=".htmx-indicator">
                    ID
                </th>
                <th hx-get="{% url 'radio:order-radios-by-name' %}"
                    hx-target="#radioTbody">
                    Nome
                </th>
                <th hx-get="{% url 'radio:order-radios-by-dial' %}"
                    hx-target="#radioTbody">
                    Dial
                </th>
                <th>Cidade
                    <select name="id_city" id=""
                            hx-get="{% url 'radio:list-radios' %}"
                            hx-target="#radioTbody">
                        <option value="">------</option>
                        {% for city in cities %}
                            <option value="{{ city.id }}"
                                    {% if id_city == city.id %}selected{% endif %}
                            >{{ city }}</option>
                        {% endfor %}
                    </select>
                </th>
            </tr>
        </thead>
        <tbody id="radioTbody">
            {% include "./radio_table.html" %}
        </tbody>
    </table>
    <div class="viraliz"></div>
{% endblock content %}

templates/radio/radio_table.html
<!-- radio_table.html -->
{% for object in radios %}
    {% include "./hx/radio_result_hx.html" %}
{% endfor %}