app/urls.py
from django.contrib import admin
from django.urls import path, include

from tasks.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("radios/", include("radio.urls")),
    path("twitch/", include("twitch.urls"))
]

radio/urls.py
from django.urls import path
from . import views as v

app_name = "radio"

urlpatterns = [
    path("", v.list_radios, name="list-radios"),
    path("", v.order_radios_by_dial, name="order-radios-by-dial"),
    path("", v.order_radios_by_name, name="order-radios-by-name"),
    path("", v.order_radios_by_id, name="order-radios-by-id"),
    path("add/", v.add_radios, name="add-radios"),
]

tasks/urls.py
from django.urls import path

from . import views as v

app_name = "tasks"

urlpatterns = [
    # path("", v.index, name="index"),
    path("", v.TaskListListView.as_view(), name="tasklist-list"),
    path("filter/", v.TaskListFilterView.as_view(), name="tasklist-filter"),
    path("create/", v.TaskListCreateView.as_view(), name="tasklist-create"),
    path("<slug:slug>/", v.TaskListDetailView.as_view(), name="tasklist-detail"),
    path(
        "<slug:slug>/add_task/", v.TaskListAddTaskView.as_view(), name="tasklist-add-task"
    ),
    # path("tasks/", include("tasker.tasks.urls")),
    # path("radios/", include("radio.urls")),
    # path("twitch/", include("twitch.urls"))
]

twitch/urls.py
from django.urls import path

from . import views as v

app_name = 'twitch'

urlpatterns = [
    path('', v.index, name="list-twitch"),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/2aaa0bfb6c.js" crossorigin="anonymous"></script>
    <title>Task Lists</title>
</head>

<body>
<div class="container">
    {% block nav %}
        {% include './nav.html' %}
    {% endblock nav %}

    {% block content %}
    {% endblock content %}
</div>

<script src="https://unpkg.com/htmx.org@0.3.0"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

{% block extrascripts %}
{% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h3>Welcome guys!</h3>
{% endblock %}

templates/nav.html
{% block nav %}
<div class="row my-3">
    <div class="col">
        <a href="{% url 'index' %}">
            <h3><i class="fas fa-tasks"></i>Home</h3>
        </a>
    </div>
    <div class="col">
        <a href="{% url 'tasks:tasklist-list' %}">
            <h3><i class="fas fa-tasks"></i> Task Lists</h3>
        </a>
    </div>
    <div class="col">
        <a href="{% url 'radio:list-radios' %}">
            <h3><i class="fas fa-tasks"></i>Radio Lists</h3>
        </a>
    </div>
    <div class="col">
        <a href="{% url 'twitch:list-twitch' %}">
            <h3><i class="fas fa-tasks"></i>Twitch Lists</h3>
        </a>
    </div>
</div>
{% endblock nav %}