app/urls.py
from django.contrib import admin
from django.urls import path, include

from tasks.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls),
    path("tasks/", include("tasks.urls")),
    path("radios/", include("radio.urls")),
    path("twitch/", include("twitch.urls"))
]

tasks/urls.py
from django.urls import path

from . import views as v

app_name = "tasks"

urlpatterns = [
    # path("", v.index, name="index"),
    path("", v.TaskListListView.as_view(), name="tasklist-list"),
    path("filter/", v.TaskListFilterView.as_view(), name="tasklist-filter"),
    path("create/", v.TaskListCreateView.as_view(), name="tasklist-create"),
    path("<slug:slug>/", v.TaskListDetailView.as_view(), name="tasklist-detail"),
    path(
        "<slug:slug>/add_task/", v.TaskListAddTaskView.as_view(), name="tasklist-add-task"
    ),
    # path("tasks/", include("tasker.tasks.urls")),
    # path("radios/", include("radio.urls")),
    # path("twitch/", include("twitch.urls"))
]

tasks/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.urls import reverse


class TaskList(models.Model):
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)

    tasks: QuerySet["Task"]

    class Meta:
        verbose_name = "Task List"
        verbose_name_plural = "Task Lists"

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse("tasks:tasklist-detail", kwargs={"slug": self.slug})

    @property
    def is_complete(self) -> bool:
        return not self.tasks.filter(is_done=False).exists()

    @property
    def complete_tasks(self) -> models.QuerySet["Task"]:
        return self.tasks.filter(is_done=True)

    @property
    def incomplete_tasks(self) -> models.QuerySet["Task"]:
        return self.tasks.filter(is_done=False)


class Task(models.Model):
    task_list = models.ForeignKey(
        TaskList,
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Task Item"
        verbose_name_plural = "Task Items"

    def __str__(self) -> str:
        return self.name

tasks/forms.py
from django import forms
from django.utils.text import slugify
from .models import TaskList


class TaskListCreateForm(forms.ModelForm):
    slug = forms.CharField(required=False, widget=forms.widgets.HiddenInput())

    class Meta:
        model = TaskList
        fields = ("name", "slug")

    def clean_name(self) -> str:
        name: str = self.cleaned_data["name"]
        slug = slugify(name)
        if TaskList.objects.filter(slug=slug).exists():
            raise forms.ValidationError(f"A Task List with the name {name} exists")
        return name

    def save(self, commit: bool = True) -> TaskList:
        task_list: TaskList = super().save(commit)
        task_list.slug = slugify(task_list.name)
        task_list.save()
        return task_list

tasks/views.py
import json
from typing import Any, Dict, List, cast

from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView
from django_filters.views import FilterView
from django.forms.models import BaseModelForm
from django.http import HttpResponse, HttpRequest

from tasks.filters import TaskListFilter
from tasks.forms import TaskListCreateForm
from tasks.models import TaskList


def index(request):
    return render(request, 'index.html')


class TaskListListView(ListView):
    model = TaskList

    def get_context_data(self, **kwargs: Dict[str, Any]) -> Dict[str, Any]:
        return super().get_context_data(
            form=TaskListCreateForm(), filterset=TaskListFilter, **kwargs
        )


class TaskListFilterView(FilterView):
    filterset_class = TaskListFilter


class TaskListCreateView(CreateView):
    model = TaskList
    form_class = TaskListCreateForm
    template_name = "tasks/tasklist_create_form.html"

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        task_list = form.save()
        response = HttpResponse()
        response["HX-Trigger"] = json.dumps(
            {"redirect": {"url": task_list.get_absolute_url()}}
        )
        return response


class TaskListDetailView(DetailView):
    model = TaskList


class TaskListAddTaskView(DetailView):
    model = TaskList
    template_name = "tasks/tasklist_tasks.html"

    def post(
            self, request: HttpRequest, *args: List[Any], **kwargs: Dict[str, Any]
    ) -> HttpResponse:
        cast(TaskList, self.get_object()).tasks.create()
        return self.get(request, *args, **kwargs)

templates/tasks/tasklist_create_form.html
<div id="tasker-list-form">
  <form>
    {% csrf_token %}
    <div class="form-row mb-2">
      <div class="col">
        <input class="form-control
          {% if form.name.errors %}
            is-invalid
          {% endif %}
          " id="id_name" name="name" placeholder="Name" {% if form.name.value %} value="{{ form.name.value }}"
          {% endif %}>

        <div class="invalid-feedback">
          {{ form.name.errors }}
        </div>

      </div>
    </div>
    <div class="form-row">
      <div class="col">
        <button class="btn btn-primary"
            hx-post="{% url 'tasks:tasklist-create' %}"
            hx-swap="outerHTML"
            hx-target="#tasker-list-form"
        >Create</button>
      </div>
    </div>
  </form>
</div>

templates/tasks/tasklist_detail.html
{% extends "base.html" %}

{% block content %}
<div class="card">
  <table class="table table-striped m-0">
    <thead>
      <tr>
        <th class="border-0" scope="col">{{ tasklist.name }}</th>
      </tr>
    </thead>
    <tbody id="tasklist-tasks">
      {% include "tasks/tasklist_tasks.html" with tasklist=tasklist %}
    </tbody>
  </table>
  <div class="card-body px-3">
    <form hx-post="{% url 'tasks:tasklist-add-task' slug=tasklist.slug %}" hx-target="#tasklist-tasks">
      {% csrf_token %}
      <button type="submit" class="btn btn-outline-primary btn-sm">
        <i class="fas fa-plus"></i>
        Add Task
      </button>
    </form>
  </div>
</div>
{% endblock %}

templates/tasks/tasklist_filter.html
<div class="card">
  <table class="table table-striped m-0">
    <thead>
      <tr>
        <th class="border-0" scope="col">Name</th>
        <th class="border-0" scope="col">Incomplete Tasks</th>
        <th class="border-0" scope="col">Complete Tasks</th>
      </tr>
    </thead>
    <tbody>
      {% for tasklist in object_list %}
      <tr>
        <th class="border-0" scope="row">
          <a href="{{ tasklist.get_absolute_url }}">
            {{ tasklist.name }}
          </a>
        </th>
        <td class="border-0">{{ tasklist.complete_tasks.count }}</td>
        <td class="border-0">{{ tasklist.incomplete_tasks.count }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

templates/tasks/tasklist_list.html
{% extends "base.html" %}


{% block content %}
<div class="row mb-2">
  <div class="col-9">
    <form hx-trigger="keyup,mouseup delay:100ms"
          hx-get="{% url 'tasks:tasklist-filter' %}"
          hx-target="#tasklist-table">
      <div class="form-row">
        <div class="col">
          <div class="input-group mb-2">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fas fa-search"></i></div>
            </div>
            <input name="name" class="form-control" id="id_name" placeholder="Search Task Lists">
          </div>
        </div>
        <div class="col pt-2">
          {% for choice in filterset.form.completeness.field.choices %}
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="completeness" id="id_completeness_{{ forloop.counter }}"
              value="{{ choice.0 }}" {% if forloop.counter == 1 %}checked{% endif %}>
            <label class="form-check-label" for="id_completeness_{{ forloop.counter }}">{{ choice.1 }}</label>
          </div>
          {% endfor %}
        </div>
      </div>
    </form>
  </div>
  <div class="col-3 text-right">
    <!-- Example single danger button -->
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createModal">
      <i class="fas fa-plus"></i>
      Create Task List
    </button>

    <!-- Modal -->
    <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header border-0 pb-0">
            <h5 class="modal-title" id="createModalLabel">Create Task List</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% include "tasks/tasklist_create_form.html" %}
          </div>
        </div>
      </div>
    </div>
    <!-- !Modal -->
  </div>
</div>

<div id="tasklist-table">
  {% include "tasks/tasklist_filter.html" %}
</div>

{% endblock %}

{% block extrascripts %}
<script type="text/javascript">
  document.addEventListener("redirect", evt => {
    console.log(evt);
    window.location.href = evt.detail.url;
  });
  htmx.logAll();
</script>
{% endblock %}

templates/tasks/tasklist_tasks.html
{% for task in tasklist.tasks.all %}
<tr>
  <td class="border-0" scope="row">
    task: {{ task.name }}
  </td>
</tr>
{% endfor %}